# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dda5f163d53990a400d691fafff3d27ae58bbe402242ff647ba46c6856e2b3504de627b9509aea6c94bc0c3816eb8ddc7d5e9197d5cfe7845599f21221276986

test:
  secret_key_base: 5112e71d0ff6cde0d4992963b23995103d3596c6a04e5c315f91f3365ee20207bc3048bdb097077aefc7d701c3333f8f01c575a4bbe93a7b22b1dffa3117d37b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
